# Week 1 Day 2 lab

## Topics that we will cover

1. For loops
2. Range
3. Functions

## For loops

In [ ]:
# Block 1 - Print all the items in the list by using a for loop

my_list = [1,2,3,4,5,6,7,8,9,10]

In [ ]:
# BLOCK 2  - Print all the items in the list using a for loop

favorite_animals = ["snakes", "seals", "bunnies", "cats"]

In [ ]:
# Challenge - From the list = [14, 18, 20, 30, 38, 42, 45, 50, 55, 100, 120] print the elements which are divisible by 5 and less than 50

## Range

In [ ]:
# Block 3 - Use range() to print the numbers 0-9

In [ ]:
# Block 4 - Print the numbers between 1 and 15 using range

In [ ]:
# BLOCK 5 - Print the numbers between 6-12 using range

In [ ]:
# Block 6 - Print the multiples of 5 between 5 and 20 using range

In [ ]:
# BLOCK 7 - Store a list containing the numbers 1-10. 
# Use a for loop to print out each number times 5

In [ ]:
# BLOCK 8 - Use a for loop to store the numbers 0-10 in a list

Challenge - print the followoing
![Image](https://www.linkpicture.com/q/CodeTriangle.png)

In [ ]:
# Challenge

In [ ]:
# Block 9 - Copy the code sent by your TA in the chat and run it.
# Is the output what you expected?

In [ ]:
# Block 10 - Copy the code sent by your TA in the chat and run it.
# Is the output what you expected?

## Functions

In [ ]:
# BLOCK 11 - Define a function addition which prints the addition of x and y

In [ ]:
# BLOCK 12 - Call the function addition

In [ ]:
# BLOCK 13 - Define a function subtraction that prints the subtraction of x and y

In [ ]:
# BLOCK 14 - Call the function subtraction

In [ ]:
# BLOCK 15 - Redefine addition to instead return the addition of x and y

In [ ]:
# BLOCK 16 - Call the function addition and store the result in a new variable

In [ ]:
# BLOCK 17 - Define a function called multiply that multiplies two numbers
# and returns the result

In [ ]:
#BLOCK 18 - Call the function multiply and store the result in a new variable

In [ ]:
# Block 19 - Copy and paste the code given to you by your TA to 
# run this block to define the function 'compare'

In [ ]:
# Block 20 - Call the function 'compare'

In [ ]:
# Block 21 - Can you modify the code in Block 19 to store the indices of the 
#agreeing numbers on the list?

In [ ]:
# Block 22 -Copy the code sent by your TA in the chat and run it.

In [ ]:
# BLOCK 23 - Call the function guess_lucky

## Putting it together - linear search

In [ ]:
# BLOCK 24 - Define a list containing the multiples of 2 from 2-14
# bonus - use a for loop!

In [ ]:
# BLOCK 25 - Find the index of the number 6

In [ ]:
# BLOCK 26 - Write a function that does linear search!

In [ ]:
# BLOCK 27 - Call the function

## More Practice and Challenges

In [ ]:
# Reverse the list_num = [1,2,3,4,5] using a for loop

In [ ]:
# Write a function that returns the min of 4 numbers

In [ ]:
# Write a function that checks to see if a number is within that range 10-25

In [ ]:
# Write a function that converts inches to feet and inches (eg 14 inchs to 1 foot 2 inches)

In [ ]:
# Print the numbers from 0 to 10 except 2 and 5 (Hint use continue)

In [ ]:
# For the numbers 1-50 print ^ if it is a multiple of 6 and print * if it is a multiple
# of 5, if it is both print ^*